version: '2'
services:
  php:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: kantaria
      MYSQL_USER: kantaria
      MYSQL_PASSWORD: kantaria
      MYSQL_ROOT_PASSWORD: kantaria