version: '2'
services:
  php:
    build:
      context: .
      dockerfile: build/apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: kantaria
      MYSQL_USER: kantaria
      MYSQL_PASSWORD: kantaria
      MYSQL_ROOT_PASSWORD: kantaria
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
      driver: local